name: Main Entry Workflow

on:
  pull_request:
    types: [labeled, opened, closed] # skapar PR, gör push, stänger manuellt
    # types: [opened, synchronize, closed] # skapar PR, gör push, stänger manuellt
  pull_request_review:
    types: [submitted] # code review
  push:
    tags:
      - 'v[1-6]\.[0-9]+\.[0-9]+'
      - 'v10\.[0-9]+\.[0-9]+'
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "event.action: ${{ github.event.action || '' }}"
          echo "review_state: ${{ github.event.review.state || '' }}"
  #       echo "event: ${{ toJson(github.event) }}"

  call-decider:
    uses: bth-python/utils/.github/workflows/decider.yml@main
    with:
      course_id: ${{ vars.COURSE_ID }}
      available_assignments: ${{ vars.ASSIGNMENTS }}
      student_id: ${{ vars.STUDENT_CANVAS_ID }}
      kmom_paths: ${{ vars.KMOM_PATHS }}
    secrets: inherit
